import type { PortfolioProject } from '@/lib/types'

export const projects: PortfolioProject[] = [
  {
    slug: 'linkedin-webscraper',
    title: 'LinkedIn Job Scraping & Data Export Pipeline',
    repo: 'https://github.com/ricardogr07/LinkedInWebScraper',
    visibility: 'public',
    featured: true,
    categories: ['web-scraping', 'automation', 'data-engineering'],
    summary:
      'Python scraping pipeline that collects job listings, normalizes records, persists run history in SQLite, and exports datasets through CLI workflows.',
    problem:
      'Teams often need recurring job-market or competitive-market datasets, but manual collection is slow, inconsistent, and hard to reuse.',
    solution:
      'Built a Python scraping pipeline that collects job listings, normalizes records, persists run history, and exports reusable datasets through CLI workflows.',
    deliverables: [
      'Scraping library',
      'CLI commands',
      'SQLite-backed persistence',
      'Export workflows',
      'Managed artifacts',
      'Documentation',
      'CI/docs/release automation',
      'Optional OpenAI enrichment',
    ],
    techStack: [
      'Python',
      'SQLite',
      'CLI tooling',
      'TOML config',
      'GitHub Actions',
      'PyPI',
      'OpenAI API',
    ],
    servicesSupported: [
      'Web Scraping',
      'Data Extraction',
      'Python Automation',
      'ETL Pipelines',
      'Reporting Automation',
    ],
    businessValue: [
      'Turns manual job-market research into an automated, repeatable data product',
      'CLI-driven — anyone on the team can run it, not just the person who built it',
      'SQLite history lets you track market changes over time without re-scraping from scratch',
      'Optional OpenAI enrichment adds structured tagging to raw scraped records',
    ],
  },
  {
    slug: 'mx-jobs-insights',
    title: 'Mexico Jobs Analytics Pipeline',
    repo: 'https://github.com/ricardogr07/mx-jobs-insights',
    docsUrl: 'https://ricardogr07.github.io/mx-jobs-insights/',
    visibility: 'public',
    featured: true,
    categories: ['data-engineering', 'automation', 'dashboard'],
    summary:
      'Analytics pipeline that transforms raw job snapshots into curated DuckDB/Parquet datasets, bilingual reports, and a public MkDocs documentation site.',
    problem:
      'Raw job listing snapshots are useful only if they become clean, queryable, repeatable analytics assets.',
    solution:
      'Built an analytics pipeline that transforms raw job snapshots into curated datasets, bilingual reports, and a public documentation site with automated publishing.',
    deliverables: [
      'Curated DuckDB/Parquet datasets',
      'Weekly/monthly bilingual reports',
      'Public MkDocs site',
      'GitHub Actions workflow',
      'Local/cloud execution paths',
      'Reproducible pipeline CLI',
    ],
    techStack: [
      'Python',
      'DuckDB',
      'Parquet',
      'MkDocs',
      'GitHub Actions',
      'Cloud Run-ready workflow',
    ],
    servicesSupported: [
      'Data Engineering',
      'ETL Pipelines',
      'Business Analytics',
      'Dashboard/Reporting Automation',
      'Cloud Application Development',
    ],
    businessValue: [
      'Delivers a public analytics site that updates automatically — not a one-time report',
      'DuckDB + Parquet keeps the dataset queryable and shareable without a database server',
      'Bilingual outputs serve both English and Spanish stakeholders from the same pipeline',
      'GitHub Actions workflow means zero manual intervention after initial setup',
    ],
  },
  {
    slug: 'reposage',
    title: 'RepoSage: AI-Assisted Repository Audit Tool',
    repo: 'https://github.com/ricardogr07/reposage',
    visibility: 'public',
    featured: true,
    categories: ['developer-tooling', 'automation', 'rag-llm'],
    summary:
      'Repository analysis tool that scans codebases, detects language and framework signals, summarizes dependencies, and outputs structured Markdown or JSON audit reports.',
    problem:
      "Engineering teams need quick codebase audits, but 'chat with your repo' tools often produce vague output without deterministic evidence.",
    solution:
      'Built a repository analysis tool that scans codebases, detects language/framework signals, summarizes dependencies, checks tests/docs/CI/typing/linting, and outputs structured Markdown or JSON reports.',
    deliverables: [
      'Local repo scanner',
      'Language/framework detection',
      'Dependency and manifest analysis',
      'Quality heuristics',
      'Markdown/JSON audit reports',
      'Optional AI enrichment',
      'GitHub Action integration',
    ],
    techStack: [
      'Python',
      'CLI tooling',
      'GitHub Actions',
      'JSON/Markdown reporting',
      'Optional OpenAI/Anthropic enrichment',
    ],
    servicesSupported: [
      'AI Automation',
      'Developer Tooling',
      'Codebase Audit',
      'Software Quality',
      'Technical Documentation',
    ],
    businessValue: [
      'Gives engineering managers an instant quality snapshot of any codebase without reading it',
      'Deterministic, structured output can be integrated into CI or PR review flows',
      'Markdown/JSON reports feed other tools — ticketing systems, dashboards, LLM summarizers',
      'Optional AI enrichment adds natural language explanations on top of raw heuristics',
    ],
  },
  {
    slug: 'rusty-rag-chunker',
    title: 'Rust + Python RAG Chunking Pipeline',
    repo: 'https://github.com/ricardogr07/rusty-rag-chunker',
    visibility: 'public',
    featured: true,
    categories: ['rag-llm', 'backend-api', 'developer-tooling'],
    summary:
      'Token-aware RAG ingestion pipeline where Rust handles performance-critical chunking via PyO3, Python orchestrates embeddings, and Qdrant stores searchable vectors.',
    problem:
      'Naive text chunking can exceed embedding model token limits, cause truncation, and degrade retrieval quality.',
    solution:
      'Built a token-aware RAG ingestion pipeline where Rust handles performance-critical chunking, Python orchestrates embeddings and retrieval, and Qdrant stores searchable vectors.',
    deliverables: [
      'Rust tokenizer/chunker exposed to Python through PyO3',
      'Python orchestration package',
      'Qdrant vector store integration',
      'CLI commands for ingest/search/ask',
      'Local and OpenAI embedding paths',
      'Hallucination guard',
      'Benchmark results',
    ],
    techStack: [
      'Rust',
      'PyO3',
      'Python',
      'Qdrant',
      'tiktoken-rs',
      'OpenAI embeddings',
      'sentence-transformers',
      'Docker',
    ],
    servicesSupported: [
      'RAG Pipelines',
      'Python/Rust Integration',
      'Vector Search',
      'LLM Tooling',
      'Performance Optimization',
    ],
    businessValue: [
      'Rust chunking eliminates token overflow failures that silently degrade retrieval quality in pure-Python stacks',
      'PyO3 bridge gives you Rust performance without rewriting your existing Python workflow',
      'Hallucination guard reduces the risk of confident wrong answers from the LLM layer',
      'Pluggable embeddings: OpenAI for quality, local sentence-transformers to cut API costs',
    ],
  },
  {
    slug: 'clipsmith',
    title: 'Clipsmith: AI-Assisted Twitch Clip Pipeline',
    repo: 'https://github.com/ricardogr07/clipsmith',
    visibility: 'public',
    featured: true,
    categories: ['media-automation', 'automation', 'rag-llm'],
    summary:
      'Local media automation pipeline that downloads VODs, transcribes Spanish audio, ranks candidate moments by chat activity, uses an LLM to select highlights, and cuts 9:16 MP4 clips.',
    problem:
      'Turning long streams or recordings into short-form vertical clips is repetitive, slow, and hard to prioritize manually.',
    solution:
      'Built a local media automation pipeline that downloads VODs, transcribes Spanish audio, ranks candidate moments by chat activity, uses an LLM to select highlights, and cuts 9:16 MP4 clips with optional captions and reframing.',
    deliverables: [
      'Local CLI',
      'Twitch VOD ingestion',
      'Spanish transcription',
      'Chat replay parsing',
      'Candidate scoring',
      'LLM-assisted clip selection',
      'FFmpeg clip generation',
      'Optional captions',
      'Optional webcam/gameplay stacked layout',
      'FastAPI/dashboard path',
    ],
    techStack: [
      'Python',
      'FFmpeg',
      'faster-whisper',
      'chat-downloader',
      'twitch-dl',
      'OpenAI/Anthropic/Ollama',
      'FastAPI',
      'Next.js',
    ],
    servicesSupported: [
      'AI Media Automation',
      'Video Processing',
      'Speech-to-Text Pipelines',
      'LLM-Assisted Content Selection',
      'Creator Tooling',
    ],
    businessValue: [
      'Turns a 4-hour VOD into 5 ready-to-post vertical clips without a video editor',
      'Chat-replay scoring prioritizes moments the audience already validated — not guesswork',
      'LLM selection adds context-awareness that pure engagement metrics miss',
      'Stacked 9:16 layout works directly for TikTok, Reels, and YouTube Shorts',
    ],
  },
  {
    slug: 'purkinje-uv',
    title: 'PurkinjeUV: Scientific Python Package for Cardiac Simulation',
    repo: 'https://github.com/ricardogr07/purkinje-uv',
    visibility: 'public',
    featured: true,
    categories: ['scientific-python', 'automation'],
    summary:
      'Modular scientific Python package for generating Purkinje-network geometries over cardiac surface meshes, with simulation, visualization, and PyPI packaging.',
    problem:
      'Computational modeling workflows need reusable, testable, documented package code instead of fragile research scripts.',
    solution:
      'Built a modular scientific Python package for generating Purkinje-network geometries over cardiac surface meshes, with simulation, visualization, export utilities, documentation, tests, and PyPI packaging.',
    deliverables: [
      'Python package',
      'Fractal network generation',
      'Mesh support',
      'UV mapping workflow',
      'Eikonal solver path',
      'Visualization utilities',
      'Docs',
      'CI',
      'PyPI release',
    ],
    techStack: [
      'Python',
      'NumPy',
      'PyVista',
      'VTK',
      'GMSH',
      'Scientific computing',
      'GitHub Actions',
      'PyPI',
    ],
    servicesSupported: [
      'Scientific Python',
      'Simulation Tools',
      'Research Software Engineering',
      'Package Development',
      'Computational Modeling',
    ],
    businessValue: [
      'Installable package means collaborators reproduce results without re-reading your setup notes',
      'PyPI release makes the work citable and verifiable outside the lab',
      'Fractal generation + UV mapping handles geometry that pure FEM mesh tools cannot address',
      'Tests + CI keep the package reliable as scientific dependencies evolve',
    ],
  },
  {
    slug: 'market-lab',
    title: 'MarketLab: Reproducible Market Experiment Platform',
    repo: 'https://github.com/ricardogr07/market-lab',
    visibility: 'public',
    featured: false,
    categories: ['ml', 'data-engineering', 'automation'],
    summary:
      'Package-first research toolkit for market experiments: data preparation, baselines, ML model training, walk-forward evaluation, diagnostics, reports, and paper-trading workflows.',
    problem:
      'Financial experiments often become messy notebooks with unclear assumptions, weak validation, and unreproducible results.',
    solution:
      'Built a package-first research toolkit for market experiments, including data preparation, baselines, ML model training, walk-forward evaluation, diagnostics, reports, and paper-trading workflows.',
    deliverables: [
      'Experiment configs',
      'Data preparation pipeline',
      'Baseline strategies',
      'ML model training workflows',
      'Walk-forward folds',
      'Diagnostics',
      'Reports and plots',
      'Local paper-trading MVP',
      'Docker/MCP server path',
    ],
    techStack: [
      'Python',
      'pandas',
      'scikit-learn',
      'Docker',
      'YAML configs',
      'Alpaca paper trading',
      'MCP tooling',
    ],
    servicesSupported: [
      'ML Prototyping',
      'Data Science Pipelines',
      'Experiment Tracking',
      'Financial Analytics',
      'Python Automation',
    ],
    businessValue: [
      'Package-first structure means experiments are reproducible — not just notebooks that ran once',
      'Walk-forward evaluation avoids look-ahead bias that invalidates most notebook backtests',
      'YAML configs make it easy to hand off experiments to another engineer or stakeholder',
    ],
  },
  {
    slug: 'myocardial-mesh',
    title: 'Myocardial Mesh Scientific Python Library',
    repo: 'https://github.com/ricardogr07/purkinje-learning-myocardial-mesh',
    visibility: 'public',
    featured: false,
    categories: ['scientific-python'],
    summary:
      'Refactored and packaged myocardial mesh utilities into a maintainable Python library for computational cardiology workflows.',
    problem:
      'Research code around myocardial mesh processing and Purkinje-fiber modeling needed packaging, maintainability, and reproducible structure.',
    solution:
      'Refactored and packaged myocardial mesh utilities into a maintainable Python library for computational cardiology workflows.',
    deliverables: [
      'Installable package',
      'Mesh parsing/manipulation',
      'Purkinje geometry integration',
      'Simulation environment support',
      'pytest-compatible structure',
      'Release/versioning setup',
    ],
    techStack: ['Python', 'NumPy', 'VTK', 'pytest', 'pyproject.toml', 'Scientific computing'],
    servicesSupported: [
      'Scientific Python',
      'Research Software Engineering',
      'Simulation Tooling',
      'Package Refactoring',
    ],
    businessValue: [
      'Installable package structure replaces copy-paste scripts that break between collaborators',
      'pytest-compatible layout means the library can be validated in CI alongside other tools',
    ],
  },
  {
    slug: 'jax-bo',
    title: 'JAX-BO: Bayesian Optimization Library Maintenance',
    repo: 'https://github.com/ricardogr07/JAX-BO',
    visibility: 'public',
    featured: false,
    categories: ['ml', 'scientific-python', 'developer-tooling'],
    summary:
      'Modernized a Bayesian Optimization library for current Python/JAX versions, improving documentation, testing demos, and expanding optimizer functionality.',
    problem: 'Research libraries often break as Python and core ML dependencies evolve.',
    solution:
      'Modernized a Bayesian Optimization library for current Python/JAX versions, improved documentation, tested demos, added logging/error handling, and expanded optimizer functionality.',
    deliverables: [
      'Python/JAX compatibility updates',
      'PyPI install path',
      'Documentation improvements',
      'Error handling/logging',
      'Optimizer refactoring',
      'Tested demos/examples',
    ],
    techStack: ['Python', 'JAX', 'Bayesian Optimization', 'Gaussian Processes', 'PyPI'],
    servicesSupported: [
      'ML Research Tooling',
      'Bayesian Optimization',
      'Scientific Python',
      'Package Maintenance',
    ],
    businessValue: [
      'Keeps the library usable as Python and JAX versions advance — no forking required',
      'Improved docs and tested examples reduce onboarding time for new contributors',
    ],
  },
  {
    slug: 'query-lab-demo',
    title: 'Portfolio Query Lab',
    liveUrl: '/demo/query-lab',
    visibility: 'demo-only',
    featured: false,
    categories: ['data-engineering', 'dashboard'],
    summary:
      'Interactive SQLite query lab running in the browser via sql.js/WebAssembly. Query synthetic portfolio holdings, monthly returns, and goals with plain SQL — no server, no backend.',
    problem:
      'Showing SQL and data-engineering skills on a portfolio requires either a live backend (operational cost, attack surface) or a restricted sandbox. Neither is ideal for an always-on public demo.',
    solution:
      'Embedded SQLite directly in the browser using sql.js (SQLite compiled to WASM). The engine loads once, populates three tables from synthetic portfolio data, and executes arbitrary SQL client-side — zero server required.',
    deliverables: [
      'In-browser SQLite via sql.js/WASM (no backend)',
      'Three queryable tables: holdings, monthly_returns, goals',
      'Seven preset queries covering aggregation, filtering, and alpha calculation',
      'Live SQL editor with syntax-aware results table',
      'Schema reference sidebar',
      'Demo banner — all data synthetic',
    ],
    techStack: ['sql.js', 'WebAssembly', 'Next.js 16', 'TypeScript', 'Tailwind v4', 'React 19'],
    servicesSupported: [
      'Data Engineering',
      'SQL Analytics',
      'Dashboard Development',
      'ETL Pipelines',
      'Python Automation',
    ],
    businessValue: [
      'Proves SQL fluency interactively — visitors run real queries, not just see screenshots',
      'Zero backend means zero ops cost and no attack surface for a public demo',
      'WASM-based SQLite is the same engine used in DuckDB-style analytical pipelines',
      'Preset queries demonstrate aggregation, time-series, and goal-tracking patterns relevant to data-engineering clients',
    ],
  },
  {
    slug: 'financial-dashboard-demo',
    title: 'Financial Data Dashboard Demo',
    liveUrl: '/demo/financial-dashboard',
    visibility: 'demo-only',
    featured: false,
    categories: ['dashboard', 'data-engineering'],
    summary:
      'End-to-end demo of a personal finance dashboard: synthetic brokerage statements ingested by a Python ETL pipeline into DuckDB, surfaced as a React/Next.js allocation and performance dashboard.',
    problem:
      'Personal finance data is highly sensitive — demonstrating a real brokerage dashboard publicly is not an option. Yet the engineering challenge of ingesting, normalizing, and visualizing statement data is real and worth showing.',
    solution:
      'Built a fully synthetic version of the private dashboard: a pipeline that parses fake PDF statements, normalizes holdings, and publishes a Next.js dashboard with allocation charts, monthly return charts, goal tracking, and an animated ETL pipeline log — all using fabricated data.',
    deliverables: [
      'Synthetic brokerage statement dataset (18 months, 8 positions)',
      'Normalized holdings and monthly-returns schema (DuckDB pattern)',
      'Allocation breakdown chart (hand-written SVG)',
      'Monthly returns chart vs benchmark (hand-written SVG)',
      'Goals and milestones tracker',
      'Animated ETL pipeline rebuild log',
      'OG image for LinkedIn Services media',
    ],
    techStack: [
      'Next.js 16',
      'TypeScript',
      'Tailwind v4',
      'React 19',
      'SVG charts',
      'DuckDB (pipeline pattern)',
      'Python ETL (pipeline pattern)',
    ],
    servicesSupported: [
      'Dashboard Development',
      'Data Engineering',
      'Financial Analytics',
      'ETL Pipelines',
      'Python Automation',
    ],
    businessValue: [
      'Proves dashboard + data pipeline skills without exposing any real financial data',
      'ETL pipeline log makes the architecture visible to non-technical stakeholders',
      'Allocation and performance charts use hand-written SVG — no runtime chart dependency',
      'Directly supports LinkedIn Services portfolio media with a public live URL',
    ],
  },
]

export const publicProjects = projects.filter((p) => p.visibility === 'public')
export const demoProjects = projects.filter((p) => p.visibility === 'demo-only')
export const visibleProjects = [...publicProjects, ...demoProjects]
export const featuredProjects = publicProjects.filter((p) => p.featured)
export const secondaryProjects = publicProjects.filter((p) => !p.featured)
